version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dropbox_clone
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    ports:
      - "5000:5000"

  frontend:
    build: ./
    ports:
      - "3000:3000"
